name: CI

on:
  push:
    branches:
      - main
      - v3
  pull_request:
    branches:
      - main
      - v3
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest] # windows-latest
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm ci
          npm --prefix test ci
      
      - name: Run tests
        run: npm t
